#!/usr/bin/env python

import os
import sys
import gzip

base_dir=sys.argv[1]
out_name = sys.argv[2]

last_source = ""
last_file = None

os.makedirs(base_dir, exist_ok=True)

for i, line in enumerate(sys.stdin):
    if i % 1000000 == 0:
        print(f"Processed {i} lines...", file=sys.stderr)
    line = line.strip()
    source = line.split('\t')[-1]
    if source != last_source:
        outfile = os.path.join(base_dir, f"{source}.{out_name}")
        if last_file is not None:
            last_file.close()
        last_file = open(outfile, 'w')
    last_source = source
    print(line, file=last_file)
